package com.dummbroke.profitpath.ui.trade_entry

import android.app.Application
import android.net.Uri
import android.os.Environment
import com.dummbroke.profitpath.core.models.Trade
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

class TradeEntryRepository(
    private val application: Application,
    private val firestore: FirebaseFirestore,
    private val auth: FirebaseAuth
) {

    suspend fun saveTrade(trade: Trade, imageUri: Uri?): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            val userId = auth.currentUser?.uid
            if (userId == null) {
                return@withContext Result.failure(Exception("User not logged in"))
            }
            trade.userId = userId
            trade.lastUpdated = Date() // Set last updated time, server will set initial timestamp

            // Handle image saving
            if (imageUri != null) {
                val imagePath = saveImageToLocalStrong(userId, imageUri)
                if (imagePath != null) {
                    trade.screenshotPath = imagePath
                } else {
                    // Optionally, decide if failing to save image is a critical error
                    // return@withContext Result.failure(Exception("Failed to save screenshot"))
                }
            }

            // Add to Firestore
            // The document ID will be auto-generated by Firestore
            firestore.collection("users").document(userId)
                .collection("trades")
                .add(trade)
                .await() // Wait for the operation to complete

            // If newBalanceAfterTrade is set and balanceUpdated is true, update profile too
            if (trade.balanceUpdated && trade.newBalanceAfterTrade != null) {
                 firestore.collection("users").document(userId)
                    .collection("profile").document("account_summary") // Assuming a single doc for summary
                    .update("currentBalance", trade.newBalanceAfterTrade)
                    .await()
            }

            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    private fun saveImageToLocalStrong(userId: String, sourceUri: Uri): String? {
        return try {
            val contentResolver = application.contentResolver
            val inputStream = contentResolver.openInputStream(sourceUri) ?: return null

            // Create a unique filename
            val timeStamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
            val imageFileName = "JPEG_${userId}_${timeStamp}_${UUID.randomUUID()}.jpg"

            // Get the app-specific directory for pictures
            // Path: /storage/emulated/0/Android/data/com.dummbroke.profitpath/files/Pictures/TradingJournal/screenshots/{userId}
            val userScreenshotsDir = File(
                application.getExternalFilesDir(Environment.DIRECTORY_PICTURES),
                "TradingJournal/screenshots/$userId"
            )

            if (!userScreenshotsDir.exists()) {
                userScreenshotsDir.mkdirs()
            }

            val imageFile = File(userScreenshotsDir, imageFileName)
            val outputStream = FileOutputStream(imageFile)

            inputStream.use { input ->
                outputStream.use { output ->
                    input.copyTo(output)
                }
            }
            imageFile.absolutePath
        } catch (e: Exception) {
            // Log error e.printStackTrace() or Timber.e(e, "Error saving image")
            null
        }
    }
} 